apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # CORS 설정 간소화
  server.enable.cors: "true"
  server.cors.allow-methods: "*"
  server.cors.allow-credentials: "false"
  server.cors.allow-origin: "*"
  server.cors.allow-headers: "*"
  # 기타 중요 서버 매개변수
  server.insecure: "true"
  server.enable.gzip: "true"
  server.log.format: "text"
  server.log.level: "debug"
