apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30081
  - name: https
    port: 443
    protocol: TCP
    # HTTPS는 8443 포트로 리다이렉션 (ArgoCD 서버의 HTTPS 포트)
    targetPort: 8443
    nodePort: 30443
  selector:
    app.kubernetes.io/name: argocd-server
