apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        args:
        - /usr/local/bin/argocd-server
        - --staticassets
        - /shared/app
        - --insecure
        - --disable-auth
        - --loglevel
        - debug
        - --rootpath
        - /
        - --basehref
        - /
        - --bindaddr
        - 0.0.0.0:8080
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true"
        - name: ARGOCD_SERVER_LOG_FORMAT
          value: "text"
        - name: ARGOCD_SERVER_LOG_LEVEL
          value: "debug"
