version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: box-recommend-postgres
    environment:
      POSTGRES_USER: test1234
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: boxrecommend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: