spring:
  config:
    activate:
      on-profile: 'default'
  datasource:
    url: jdbc:postgresql://localhost:5433/boxrecommend
    password: test1234
    username: test1234
    driver-class-name: org.postgresql.Driver
  application:
    name: box-recommend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  sql:
    init:
      schema-locations:
        - classpath:/db/init.sql
        - classpath:/db/insert_data.sql
      mode: always
server:
  port: 8888

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
    default-models-expand-depth: 2
    default-model-expand-depth: 2
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: true
  enable-spring-security: false
  paths-to-match: /**
  paths-to-exclude:
    - /error
    - /actuator/**
  override-with-generic-response: false

# Actuator 및 Prometheus 설정
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: 'test'
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: box-recommend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:/db/insert_data.sql
      schema-locations: classpath:/db/init.sql
server:
  port: 0  # 테스트 환경에서도 랜덤 포트 사용

# Actuator 및 Prometheus 설정 (테스트 환경)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: 'prod'
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boxrecommend}
    password: ${DB_PASSWORD:test1234}
    username: ${DB_USERNAME:test1234}
    driver-class-name: org.postgresql.Driver
  application:
    name: box-recommend
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:changeme}
  sql:
    init:
      mode: never
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true