apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/configmap.yaml
  - ../../base/secret.yaml
  - ../../base/postgres.yaml
  - ../../base/box-recommend-app.yaml