apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: box-recommend-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard
    argocd.argoproj.io/sync-wave: "1"  # 데이터베이스 배포 후 애플리케이션 배포
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tianea2160/bin-packing'
    targetRevision: master
    path: base/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: box-recommend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/resources
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/readinessProbe
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/livenessProbe
  info:
    - name: Description
      value: This application deploys the box recommendation service only (without database).
  sources: []
  revisionHistoryLimit: 3
