apiVersion: v1
kind: ConfigMap
metadata:
  namespace: box-recommend
  name: box-recommend-config
  labels:
    app: box-recommend
data:
  application-prod.yml: |-
    server:
      port: 8080
    
    logging:
      level:
        root: DEBUG
        org.tianea.boxrecommend: DEBUG
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
        
    # 데이터베이스 연결 관련 설정 추가
    spring:
      datasource:
        hikari:
          connection-timeout: 30000  # 30초
          maximum-pool-size: 10
          minimum-idle: 2
          idle-timeout: 120000  # 2분
          max-lifetime: 1800000  # 30분
          connection-test-query: SELECT 1
      jpa:
        properties:
          hibernate:
            jdbc:
              batch_size: 50
            order_inserts: true
            order_updates: true
          
    management:
      endpoint:
        health:
          enabled: true
          show-details: always
        info:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,info
          base-path: /
          path-mapping:
            health: health