apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-recommend
  namespace: box-recommend
  labels:
    app: box-recommend
spec:
  replicas: 2  # 파드 2개 실행
  selector:
    matchLabels:
      app: box-recommend
  template:
    metadata:
      labels:
        app: box-recommend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: box-recommend
        image: rhlehfndvkd7557/box-recommend:latest-java21
        imagePullPolicy: Always
        # 컨테이너 시작 지연 추가
        command:
        - "sh"
        - "-c"
        - |
          echo "Waiting for database to be ready..."
          sleep 30
          java -jar /app/app.jar
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "boxrecommend"
        - name: JAVA_OPTS
          value: "-Xmx768m -Xms256m -Dlogging.level.root=DEBUG"
        # 서버 리스닝 주소를 명시적으로 설정
        - name: SERVER_ADDRESS
          value: "0.0.0.0"
        # 서버 포트 명시
        - name: SERVER_PORT
          value: "8080"
        # 시작 타임아웃 증가
        - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
          value: "30s"
        # Actuator 설정
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,prometheus,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "never"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: MANAGEMENT_METRICS_TAGS_APPLICATION
          value: "box-recommend"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: box-recommend-config