apiVersion: v1
kind: ConfigMap
metadata:
  namespace: box-recommend
  name: box-recommend-config
  labels:
    app: box-recommend
data:
  application-prod.yml: |-
    server:
      port: 8080
    
    logging:
      level:
        root: DEBUG
        org.tianea.boxrecommend: DEBUG
        org.springframework.web: DEBUG
        
    management:
      endpoint:
        health:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,info
          base-path: /
          path-mapping:
            health: health