apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# ArgoCD 설치를 위한 매니페스트 URL을 적용하는 Job
apiVersion: batch/v1
kind: Job
metadata:
  name: install-argocd
  namespace: argocd
spec:
  template:
    spec:
      serviceAccountName: argocd-installer
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      restartPolicy: OnFailure
  backoffLimit: 2
---
# Job에 필요한 ServiceAccount 및 RBAC 권한 (최소 권한 원칙 적용)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-installer
  namespace: argocd
---
# 최소 권한으로 ClusterRole 구성 - ArgoCD 설치에 필요한 권한만 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-installer
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces", "pods", "services", "secrets", "configmaps", "persistentvolumeclaims" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles", "clusterrolebindings", "roles", "rolebindings" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "get", "list", "update", "patch" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "applications", "appprojects" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-installer
subjects:
  - kind: ServiceAccount
    name: argocd-installer
    namespace: argocd
