apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # 실제 사용할 ArgoCD 인스턴스의 URL로 변경해야 합니다
  url: https://localhost:30443
  admin.enabled: "true"
  # TLS 관련 설정 추가
  tls.insecure: "true"
  # CORS 설정 추가
  application.instanceLabelKey: argocd.argoproj.io/instance
  ui.bannercontent: ""
  timeout.reconciliation: 180s
  
  # 애플리케이션 컨트롤러 설정
  controller.status.cache.normalization.enabled: "true"
  
  # 리소스 헬스 체크 커스텀 설정
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Application is healthy"
        return hs
    apps/Deployment:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.availableReplicas ~= nil and obj.status.availableReplicas > 0 then
            hs.status = "Healthy"
            hs.message = "Deployment is available"
            return hs
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for deployment"
        return hs
    v1/Service:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Service is healthy"
        return hs
