apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: box-recommend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tianea2160/bin-packing'
    targetRevision: master
    path: base/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: box-recommend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  info:
    - name: Description
      value: This application deploys the box recommendation service only (without database).
  sources: []
  # 헬스 체크 설정 추가
  revisionHistoryLimit: 3
  # 헬스 상태 커스텀 설정
  health:
    healthCheckResourcePath: 'external://google.com'  # 기본 체크에 추가
