apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: box-recommend
  namespace: box-recommend
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tianea2160/bin-packing'
    targetRevision: master
    path: overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: box-recommend
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  info:
    - name: Description
      value: This application deploys the box recommendation service.
  sources: []