apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: box-recommend-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tianea2160/bin-packing'
    targetRevision: master
    path: base/postgres
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: box-recommend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: Description
      value: PostgreSQL database for the box recommendation service.
  sources: []
  # 헬스 체크 설정 추가
  revisionHistoryLimit: 3
