apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-recommend
  namespace: box-recommend
  labels:
    app: box-recommend
spec:
  replicas: 2  # 파드 2개 실행
  selector:
    matchLabels:
      app: box-recommend
  template:
    metadata:
      labels:
        app: box-recommend
    spec:
      containers:
      - name: box-recommend
        image: box-recommend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: JAVA_OPTS
          value: "-Xmx768m -Xms256m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: box-recommend-config