apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - box-recommend-deployment.yaml
  - box-recommend-service.yaml
  - box-recommend-app.yaml
  - box-recommend-configmap.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - box-recommend-secret.yaml
  - argocd-server.yaml
  - argocd-installation.yaml
  - argocd-server-service.yaml
  - argocd-admin-password.yaml
  - argocd-config.yaml
  - argocd-cmd-params-cm.yaml

# 최신 kustomize 버전에서 권장하는 patches 구문 사용
patches:
  - path: argocd-server-deployment-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
