apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 네임스페이스 먼저 생성
  - namespace.yaml
  # ArgoCD 애플리케이션 설정
  - argocd/argocd-app.yaml
  - app/box-recommend-app.yaml
  - postgres/box-recommend-postgres-app.yaml
