apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - box-recommend-deployment.yaml
  - box-recommend-service.yaml
  - box-recommend-app.yaml
  - box-recommend-configmap.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - box-recommend-secret.yaml
  - argocd-server.yaml
  - argocd-installation.yaml
  - argocd-server-service.yaml
  - argocd-admin-password.yaml
  - argocd-config.yaml