apiVersion: v1
kind: Service
metadata:
  name: box-recommend
  labels:
    app: box-recommend
spec:
  type: NodePort
  selector:
    app: box-recommend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP