apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: box-recommend-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard
    argocd.argoproj.io/sync-wave: "0"  # 데이터베이스를 먼저 배포하도록 변경
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tianea2160/bin-packing'
    targetRevision: master
    path: base/postgres
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: box-recommend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: Description
      value: PostgreSQL database for the box recommendation service.
  sources: []
  revisionHistoryLimit: 3
